#!/usr/bin/python3
import os
from subprocess import Popen

while True:
    os.chdir("src/")
    print("\nStarting ")
    p = Popen("pipenv run python3.8 bot.py", shell=True)
    return_code = p.wait()
    print(return_code)
    if return_code == 0:
        break